apiVersion: v2
publisher: vscjava
name: vscode-java-pack
version: 0.9.1
type: VS Code extension
diplayName: Java Extension Pack
title: Java Extension Pack
description: Popular extensions for Java development and more.
icon: 
repository: https://github.com/Microsoft/vscode-java-pack
category: Editor
spec: 
  containers:
    - image: "quay.io/eclipse/che-sidecar-java:11-f76ca45"
      name: vscode-java
      memoryLimit: "2000Mi"
  extensions: 
    - https://download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.63.0-2222.vsix
    - https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-java-debug/vscode-java-debug-0.26.0.vsix
