apiVersion: v2
publisher: vscjava
name: vscode-java-pack
version: 0.9.1
type: VS Code extension
diplayName: Java Extension Pack
title: Java Extension Pack
description: Popular extensions for Java development and more.
icon: 
repository: https://github.com/Microsoft/vscode-java-pack
category: Editor
spec:
  containers:
    - image: "quay.io/eclipse/che-sidecar-java:11-f76ca45"
      name: vscode-java
      memoryLimit: "1500Mi"
      volumes:
      - mountPath: "/home/theia/.m2"
        name: m2
  extensions:
    - https://marketplace.visualstudio.com/_apis/public/gallery/publishers/redhat/vsextensions/java/0.57.0/vspackage
    - https://marketplace.visualstudio.com/_apis/public/gallery/publishers/vscjava/vsextensions/vscode-java-debug/0.24.0/vspackage
