apiVersion: v2
publisher: vscjava
name: vscode-vjava-pack
version: 0.9.1
type: VS Code extension
diplayName: Java Extension Pack
title: Java Extension Pack
description: Popular extensions for Java development and more.
icon: 
repository: https://github.com/Microsoft/vscode-java-pack
category: Editor
spec: 
  containers:
    - image: "eclipse/che-remote-plugin-runner-java11"
      name: vscode-java
      memoryLimit: "2000Mi"
  extensions: 
    - https://marketplace.visualstudio.com/_apis/public/gallery/publishers/redhat/vsextensions/java/0.63.0/vspackage
    - https://marketplace.visualstudio.com/_apis/public/gallery/publishers/VisualStudioExptTeam/vsextensions/vscodeintellicode/1.2.8/vspackage
    - https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-java-debug/vscode-java-debug-0.26.0.vsix
    - https://marketplace.visualstudio.com/_apis/public/gallery/publishers/vscjava/vsextensions/vscode-java-test/0.23.0/vspackage
