apiVersion: v2
publisher: shengchen
name: vscode-checkstyle
version: 1.3.2
type: VS Code extension
diplayName: Checkstyle for Java
title: Checkstyle for Java
description: Provide real-time feedback about Checkstyle violations and quick fix actions
icon: 
repository: https://github.com/jdneo/vscode-checkstyle
category: Linter
spec: 
  containers:
    - image: "eclipse/che-remote-plugin-runner-java11:7.3.3"
      name: checkstyle
      memoryLimit: "1500Mi"
  extensions: 
    - https://github.com/redhat-developer/vscode-java/releases/download/v0.57.0/redhat.java-0.57.0.vsix
    - https://marketplace.visualstudio.com/_apis/public/gallery/publishers/shengchen/vsextensions/vscode-checkstyle/1.3.2/vspackage
